### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by duque7x** [devRMA/python-stopwatch2#2]
# O link para a guide não funciona 

![image](https://user-images.githubusercontent.com/92229705/158872086-30d46db1-ab4a-4c0b-ab2b-a4cde851f46e.png)

**Comment by devRMA** [comment]
Olá, vi que caso clique para abrir o link em uma nova guia/janela, o link para de funcionar.

Obrigado por reportar esse bug, vou resolver ele assim que puder!

**Comment by devRMA** [comment]
@JosueHTML2 Bug corrigido no commit 6613f16f4ed409454bb4ea5944fec0db004968f5

:)
